### ISSUE TITLE
Purpose of `filter()`

### ISSUE THREAD

**Issue by anhldbk** [apollostack/graphql-anywhere#17]
I'm following the documentation of [Filtering With Fragments](http://dev.apollodata.com/react/fragments.html#filtering-with-fragments). It states that:

```text
We can also use the graphql-anywhere package to filter the exact fields from the entry before passing them to the subcomponent. 
```

But why do we need filtering? Surplus fields are ok, right?

**Comment by stubailo** [comment]
They are, but some people are interested in making sure that components don't get data they didn't ask for, for code quality reasons. Basically, you might use a field by accident that wasn't included in a fragment, and then when the parent component removes it from the query your component breaks.

People migrating from Relay to Apollo were often asking for this feature.
