### ISSUE TITLE
Is it possible to select from a Mobx Observable Object?

### ISSUE THREAD

**Issue by liveresume** [apollostack/graphql-anywhere#22]
Hopefully you have some familiarity with mobx.  If not, all it does is wrap any POJO in its own ObservableObject.  

If ObservableObject was the structure passed into graphql-anywhere, would it return the same object type? Or would it crash?

**Comment by stubailo** [comment]
Well, GraphQL-anywhere doesn't really do much for you, it just interprets the query. So if you write the right kind of resolver it should work just fine, I would guess. Have you tried it?

**Comment by liveresume** [comment]
No, just evaluating options. Will post back if I try. Thanks.

**Comment by helfer** [comment]
Going to close this issue since it's been a while.
