### ISSUE TITLE
Failed prop type: The inline argument "slug" is expected as a variable but was not provided.

### ISSUE THREAD

**Issue by sedubois** [apollostack/graphql-anywhere#24]
With my example code: https://github.com/relatemind/relate

Loading this page works fine: http://localhost:3000/profile?slug=clang

But it still gives this error in browser console: 
`Failed prop type: The inline argument "slug" is expected as a variable but was not provided.`

I'm not sure if I'm doing something wrong or if there's a bug? I defined the propType like this:
```js
import { propType } from 'graphql-anywhere';

function Profile({ data: { User } }) {
  return <div>...</div>;
}

const query = gql`
  query Profile($slug: String!) {
    User(slug: $slug) {
      ...
    }
  }
`;

Profile.propTypes = {
  data: propType(query).isRequired,
};

const withData = graphql(query, {
  options({ slug }) {
    return {
      variables: { slug },
    };
  },
});

export default withData(Profile);
```

**Comment by stubailo** [comment]
Looks like we simply forgot to make `propType` (and I would guess also `filter`) with variables. This package was originally intended for executing queries on the client where it made sense to validate the presence of variables, but the new utilities we added don't need them.

I think the best fix might be to add an option to `graphql-anywhere` called `ignoreMissingVariables` and pass that down into `argumentsObjectFromField`, what do you think?

Here's where the error is thrown from btw: https://github.com/apollostack/graphql-anywhere/blob/43f987b72ef4a6f5e9ed774e98a9521a11dabd28/src/storeUtils.ts#L64

**Comment by sedubois** [comment]
@stubailo I haven't really understood the issue so far. Currently the error message doesn't make sense, because I _did_ pass the variable.

I don't see why the propType check should ignore variables? But if that's the only way yes, better to ignore them and get rid of the error message (because as a user I can't do anything about it).

**Comment by tmeasday** [comment]
@sedubois because the `propType` check is "running" the query, just in a special way that's really just checking the shape of the data. But the value of variables is certainly irrelevant to that, unless we wanted to support `@skip` and `@include` directives I guess.

**Comment by sedubois** [comment]
Would there be any news on this? Would be great to get rid of this confusing warning 🙂

**Comment by tmeasday** [comment]
Hi @sedubois - are you interested in having a go at fixing it? I'd start by creating another test like this one: https://github.com/apollostack/graphql-anywhere/blob/master/test/utilities.ts#L8-L63 that includes a variable; then trying to follow @stubailo's [suggestion](https://github.com/apollostack/graphql-anywhere/issues/24#issuecomment-267470110)

**Comment by sedubois** [comment]
@tmeasday for now I just commented out this code 😢 I'm not familiar with Apollo's codebase and don't have time to dig in right now as I'm building the prototype https://github.com/relatenow/relate.

**Comment by helfer** [comment]
@sedubois Good news, this should work now! Please check and reopen this issue if necessary! 🙂

**Comment by sedubois** [comment]
Thanks, seems to work!
