### ISSUE TITLE
How to filter() an array of objects?

### ISSUE THREAD

**Issue by srosset81** [apollostack/graphql-anywhere#25]
Hello,

Right now the `filter` function takes an object and filter it according to a GraphQL fragment. But what if we want to pass to a component an *array of objects* because we used the fragment within a sub-field?

```js
gql`
    query getMember() {
        getMember() {
            id
            __typename
            name
            actions {
                ...ActionsSection
            }
        }
    }
    ${ActionsSection.fragments.actions}
`;
```

It seems that, in this case, we cannot use the filter() function anymore, because the filter() function cannot take an array of objects as an argument.

```jsx
<ActionsSection actions={filter(ActionsSection.fragments.actions, this.data.getMember.actions)}/>
```

On the other hand, we can still use graphql-anywhere for the propTypes, like this.

```js
ActionsSection.propTypes = {
    actions: React.PropTypes.arrayOf(propType(ActionsSection.fragments.actions)).isRequired
};
```

Any idea how this could be supported? Maybe with a new filterList() function?

**Comment by bessey** [comment]
Seems like this should just be built into filter, but in the meantime maybe this will help you:

```js
import {filter as filterItem} from "graphql-anywhere"

// Extends filter to filter each item in an array, if in an array
export function filter(doc, data) {
  if(Array.isArray(data)) {
    return data.map((item) => filterItem(doc, item))
  } else {
    return filterItem(doc, data)    
  }
}
```

**Comment by srosset81** [comment]
Thanks, that works perfectly
