### ISSUE TITLE
Attaching a schema to graphql-anywhere

### ISSUE THREAD

**Issue by sheerun** [apollostack/graphql-anywhere#7]
Hey,

I get that the idea behind graphql-anywhere is schemalessness, but I'd like to attach one to is, so I can debug it in graphiql and easily serve using apollo-server (and restrict possible set of respones).

Would it be theoretically possible? Something like:

```
const schema = attachAnywhereResolver(schema, resolver)
```

It would work the same as `addResolveFunctionsToSchema`, but resolve function would be executed for all schema fields.

**Comment by stubailo** [comment]
Why not just use graphql-js?

**Comment by stubailo** [comment]
Oh, I see what you're saying - you want the same resolver for all fields, but you do want to have a schema to validate the query.

I have an idea:

1. Write a schema in the schema language
2. Call `buildASTSchema` from graphql-js on it
3. Use that object for introspection to power graphiql
4. When the query arrives, use graphql-anywhere to run it

However, I wouldn't currently recommend using this package for a server-side API. It would probably work, but it hasn't been tested in that environment.

Another thing you could do:

1. Write a schema in the schema language
2. Call `buildASTSchema` from graphql-js on it
3. Write your own version of `addResolveFunctionsToSchema` that uses the same resolver everywhere: https://github.com/apollostack/graphql-tools/blob/e801f052f29d41828bbc97655215aa4f5d868deb/src/schemaGenerator.ts#L266

If I was trying to make a server-side API I would do the second.

**Comment by helfer** [comment]
This is a pretty old issue. Closing now.
