### ISSUE TITLE
Query against redux

### ISSUE THREAD

**Issue by jole78** [apollostack/graphql-anywhere#8]
First of all, loving this initiative...seems very promising. 
Also, not quite sure if this repo is the right place to ask but here goes...

I have used apollo client (react) to get a list of items (let's say they are organisations that have 'name', 'url' etc).
I'm presenting them in a list view but now I want to apply some filters on top of that list, one of those filters being a search by name, e.g. name startswith...

My idea was that I could use a gql query to do that (partly because the back-end graphql service already supports that argument being passed to the original query).

Now, my question is, can I somehow use this lib to basically filter against the already cached query result that is in my redux store. I've seen that there has already been some discussions on apollo client on supporting/exposing the selectors that it uses internally or possibly start using this lib internally in apollo client so it should be possible right??

**Comment by stubailo** [comment]
@jole78 this isn't really a `graphql-anywhere` question, it's more of an `apollo-client` question.

One feature we're working on for the next `apollo-client`, which has been refactored to use `graphql-anywhere`, is the ability to write custom client-side resolvers. So basically you can modify how the query reads from the cache, for example to apply an additional filter without hitting the server.

Can you give me a bit more detail about how you would use such a feature? That will help the design. Right now here is what we have:

https://meteor.quip.com/hyaMALbIQFK9

**Comment by jole78** [comment]
@stubailo yeah, wasn't quite sure as I said as to where this question would fit. Have seen that apollo-client issues have been around this topic before. Anyway...

I'll give it a go trying to explain.
I have a react component that lists all the items of a certain kind (let's say they are organisations). From a pure REST perspective that would be */organisations* but since I use apollo-client that is now a gql query, something like `{organisations { name, id, ...etc } }` 
At the top of the component I have a another component, a search bar, where the user can input something like 'git' for example.
What I'd like to do is to re-use the already cached qql query that the list view is *bound* to via the *graphql* HOC and just "filter" the query to something like `organisations(name:'git') { name, id ...etc}` and the list view should automatically now show the items that begin with a name of git...for example github, gitlab etc....

**Comment by stubailo** [comment]
I feel like the _best_ way to handle that would be to store the filter key in Redux, and then do the filter in the React component directly, rather than doing it via a custom GraphQL resolver.

But I think the new feature I'm adding would support this case if you chose to do it with a custom resolver.

**Comment by jole78** [comment]
@stubailo agreed, the way I solved it right now was to add a regular old redux connect around the gql aware component and filter the results from the gql query based on the filter in redux (in plain JS with the help of reselect). Works nice enough.
Will be interesting to see where this is going though...closing this issue. tnx for the help!
